./client.out 1 ./1-mb-file.out
./client.out 1 ./2-mb-file.out
./client.out 1 ./4-mb-file.out
./client.out 1 ./8-mb-file.out
./client.out 1 ./16-mb-file.out
./client.out 1 ./32-mb-file.out
./client.out 1 ./64-mb-file.out
./client.out 1 ./128-mb-file.out
./client.out 1 ./256-mb-file.out
./client.out 1 ./512-mb-file.out
./client.out 1 ./1-gb-file.out
